
[package]
name = "m2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
rand = "0.8.5"
actix-files = "0.6.5"
qrcode = "0.14.0"
local-ip-address = "0.6.1"
